# Generated by Django 5.2.6 on 2025-11-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_webpaypedidotransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprador_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador_nivel_acceso',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador_telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nivel_acceso',
            field=models.CharField(choices=[('publico', 'Público'), ('exclusivo', 'Exclusivo')], default='publico', max_length=20),
        ),
    ]
