# Generated by Django 5.2.8 on 2025-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoslanding',
            name='carousel_imagenes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='datoslanding',
            name='horario_domingo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datoslanding',
            name='horario_lunes_viernes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datoslanding',
            name='horario_sabado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datoslanding',
            name='membresias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='datoslanding',
            name='proximos_eventos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
