# Generated by Django 5.2.4 on 2025-11-20 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('posicion_anterior', models.IntegerField(blank=True, null=True)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('puntos_mes', models.IntegerField(default=0)),
                ('entrenamientos_asistidos', models.IntegerField(default=0)),
                ('entrenamientos_totales', models.IntegerField(default=0)),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('competencias_participadas', models.IntegerField(default=0)),
                ('medallas_oro', models.IntegerField(default=0)),
                ('medallas_plata', models.IntegerField(default=0)),
                ('medallas_bronce', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='atletas.atleta')),
            ],
            options={
                'ordering': ['posicion'],
            },
        ),
    ]
