# Generated by Django 5.2.8 on 2025-11-27 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_certificacionatleta_estado_comentario_admin'),
        ('ranking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('tecnica', 'Tecnica'), ('actitud', 'Actitud'), ('esfuerzo', 'Esfuerzo'), ('liderazgo', 'Liderazgo')], default='tecnica', max_length=30)),
                ('puntuacion', models.PositiveIntegerField(default=1)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='atletas.atleta')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogroAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('competencia', 'Competencia'), ('entrenamiento', 'Entrenamiento'), ('actitud', 'Actitud'), ('otro', 'Otro')], default='competencia', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='atletas.atleta')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
