# Generated by Django 5.2.4 on 2025-11-20 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_minima', models.IntegerField(default=5)),
                ('capacidad_maxima', models.IntegerField(default=35)),
                ('cupos_disponibles', models.IntegerField(default=35)),
                ('activo', models.BooleanField(default=True)),
                ('color', models.CharField(default='#FCD34D', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipos/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrenadores', models.ManyToManyField(blank=True, related_name='equipos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nivel', 'nombre'],
            },
        ),
    ]
