# Generated by Django 5.2.4 on 2025-11-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('arriendo', 'Arriendo'), ('materiales', 'Materiales'), ('uniformes', 'Uniformes'), ('servicios', 'Servicios'), ('personal', 'Personal'), ('otros', 'Otros')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='egresos/comprobantes/')),
                ('metodo_pago', models.CharField(default='efectivo', max_length=50)),
                ('proveedor', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
