# Generated by Django 5.2.4 on 2025-11-20 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('pago', 'Pago'), ('horario', 'Horario'), ('evento', 'Evento'), ('urgente', 'Urgente')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('canales', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('programada', 'Programada')], default='borrador', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('destinatarios', models.ManyToManyField(related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('leida_por', models.ManyToManyField(blank=True, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
