# Generated by Django 5.2.4 on 2025-11-20 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimiento', models.IntegerField(default=5)),
                ('recargo_por_atraso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_hermanos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Mensualidad',
                'verbose_name_plural': 'Configuraciones de Mensualidad',
            },
        ),
        migrations.CreateModel(
            name='PeriodoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_hermanos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('programado', 'Programado')], default='programado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/matriculas/')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='atletas.atleta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='pagos.periodomatricula')),
            ],
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('condonado', 'Condonado')], default='pendiente', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/mensualidades/')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to=settings.AUTH_USER_MODEL)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='atletas.atleta')),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('atleta', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='PagoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('matricula', 'Matrícula'), ('mensualidad', 'Mensualidad'), ('otro', 'Otro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=255)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/manuales/')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_manuales', to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.matricula')),
                ('mensualidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.mensualidad')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
