# Generated by Django 5.2.8 on 2025-11-26 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_certificacionatleta_estado_comentario_admin'),
        ('pagos', '0002_webpaytransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoOnlineObligacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/pagos_online/')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_online', to=settings.AUTH_USER_MODEL)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_online', to='atletas.atleta')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones', to='pagos.pagoonline')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('pago', 'apoderado', 'atleta')},
            },
        ),
    ]
