# Generated by Django 5.2.8 on 2025-11-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pagoonline_pagoonlineobligacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebpayPagoOnlineTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='iniciada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpay_transacciones', to='pagos.pagoonlineobligacion')),
            ],
        ),
    ]
