# Generated by Django 5.2.8 on 2025-11-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_paymentcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoonline',
            name='tipo',
            field=models.CharField(choices=[('mensualidad', 'Mensualidad'), ('competencia', 'Competencia'), ('musica', 'Musica'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
