# Generated by Django 5.2.4 on 2025-11-20 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('nivel', models.IntegerField()),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=255)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20)),
                ('alergias', models.TextField(blank=True)),
                ('condiciones_medicas', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('restricciones_fisicas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('motivo_retiro', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('asistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('historial_deportivo', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletas', to='equipos.equipo')),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='CertificacionAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('medico', 'Médico'), ('escolar', 'Escolar'), ('nacimiento', 'Nacimiento'), ('otro', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='certificaciones/atletas/')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='atletas.atleta')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
